#!/usr/bin/env perl

use strict;
use warnings;
use FindBin '$Bin';

# we start with the wordlist that is manually curated. selected words are
# indented
my %seen_4letters;
my @words;
open my $fh, "<", "$Bin/../devdata/words.txt";
while (<$fh>) {
    chomp;
    next unless /^\s+((\w{4})\w*)$/;
    next if $seen_4letters{$2}++;
    push @words, $1;
    #last if @words >= 2048;
}

warn "Only ".scalar(@words)." words\n" if @words < 2048;
print map {"$_\n"} @words;
